# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Acceptance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    # ubuntu allows for docker support - https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
    # - name: Configure git for private modules
    #   env:
    #     TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #   run: git config --global url."https://murfffi:${TOKEN}@github.com".insteadOf "https://github.com"
    - name: Test
      run: make test
    - name: Integration
      run: make itest