# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Acceptance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  e2e:
    # Only ubuntu allows for docker support - https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build
      run: go build -v ./...
    - name: Test
      run: make test
    - name: Integration # requires Docker and thus ubuntu runner
      run: make itest

  platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "windows-latest"
          - "macos-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          # use really old 1.21 version to validate claim in docs
          go-version: '1.21'
      - name: Test
        run: make test

  oldgo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.7"
      - name: Test
        run: make test